swagger: '2.0'

info:
  version: "0.0.1"
  title: Thermostat Web API
  license:
    name: GPL v2 with Classpath Exception
    url: http://www.gnu.org/licenses


consumes: ['application/json']
produces: ['application/json', 'text/html; charset=utf-8']
paths:
# Collections in 2.0: revision 3c990cdff9ad
# schema-info
  /agents/{agentId}/schema:
    parameters:
      - $ref: '#/parameters/agent-id'    
    get:
      description: Gets schema information for agent
      responses:
        401:
          $ref: '#/responses/unauthorized'
        200:
          description: Successful response
          schema:
              type: array
              items:
                $ref: '#/definitions/schema-info'
# agent-config
  /agents/{agentId}:
    parameters:
      - $ref: '#/parameters/agent-id'    
    get:
      description: Gets information for an agent. Use 'all' as the agentId
      responses:
        401:
          $ref: '#/responses/unauthorized'
        200:
          description: Successful response
          schema:
              type: array
              items:
                $ref: '#/definitions/agent-info'     
# host-info
  /agents/{agentId}/host:
    parameters:
      - $ref: '#/parameters/agent-id'
    get:
      description: Gets information for the host
      responses:
        401:
          $ref: '#/responses/unauthorized'      
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/host-info'
# network-info
# backend-info

#
# agents -> host
# agents -> jvms

# can restrict at each level (easier to do restrict to all jvms under specific host, etc.)
# agents -> host -> jvms

# Tree-based restriction (file-system-like)
# /*
# /agents/agentid/*
# agents -> host -> info
#

# numa-host-info
# numa-stat
# cpu-stats
  /agents/{agentId}/host/cpu:
    parameters:
      - $ref: '#/parameters/agent-id'
    get:
      description: Gets cpu information for the host
      responses:
        401:
          $ref: '#/responses/unauthorized'      
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/host-cpu-info'
# memory-stats

# vm-info
  /agents/{agentId}/host/vms/{vmId}:
    parameters:
      - $ref: '#/parameters/agent-id'
      - $ref: '#/parameters/vm-id'    
    get:
      description: Gets information for a jvm monitored by an agent
      responses:
        401:
          $ref: '#/responses/unauthorized'      
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/vm-info'

# vm-class-stats
# vm-gc-stats
# vm-numa-stats
# vm-cpu-stats
  /agents/{agentId}/vms/{vmId}/cpu:
    parameters:
      - $ref: '#/parameters/agent-id'
      - $ref: '#/parameters/vm-id'
    get:
      description: Gets most recent cpu information for the jvm
      parameters:
        - $ref: '#/parameters/count'
        - $ref: '#/parameters/sort'
        - $ref: '#/parameters/maxTimestamp'
        - $ref: '#/parameters/minTimestamp'
      responses:
        401:
          $ref: '#/responses/unauthorized'      
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/vm-cpu-info'
    post:
      description: Gets most recent cpu information for the jvm
      parameters:
        - $ref: '#/parameters/filters'
        - $ref: '#/parameters/count'
        - $ref: '#/parameters/sort'
      responses:
        401:
          $ref: '#/responses/unauthorized'      
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/vm-cpu-info'
    put:
      description: Adds cpu information for the jvm
      parameters:
        - $ref: '#/parameters/vm-cpu-info'
        - $ref: '#/parameters/tags'
      responses:
        401:
          $ref: '#/responses/unauthorized'      
        200:
          description: Successful response

# vm-memory-stats
# vm-io-stats
# vm-compiler-stats
# vm-heap-info
# vm-jmx-notification
# vm-jmx-notification-stats
# vm-tlab-stats


# profile-status
# profile-info

# vm-thread-summary
# vm-thread-session
# vm-thread-state

# vm-thread-lock
# vm-deadlock-data

# vm-thread-harvesting TODO: Improve collection schema and function


definitions:
  filters:
    type: array
    items:
      $ref: '#/definitions/filter'
  filter:
    type: object
    properties:
      key:
        type: string
      comparator:
        type: string
      value:
        type: string
    required:
      - key
      - comparator
      - value
      
  schema-info:
    type: object
  agent-info:
    type: object

  host-info:
    type: object
  host-cpu-info:
    type: object
    
  vm-info:
    type: object
  vm-cpu-info:
    type: object
    
parameters:
  agent-id:
    name: agentId
    in: path
    description: The agent identification number
    type: number
    required: true
  vm-id:
    name: vmId
    in: path
    description: The jvm identification number
    type: number
    required: true

  vm-cpu-info:
    name: vmCpuInfo
    in: body
    description: The jvm CPU information
    required: true
    schema:
      $ref: '#/definitions/vm-cpu-info'
    
  tags:
    name: tags
    in: query
    description: CSV of tags
    type: string
  count:
    name: count
    in: query
    description: Count of media to return.
    type: integer
  filters:
    name: filters
    in: body
    description: Key, Comparator, Value trios to filter the data
    schema:
      $ref: '#/definitions/filters'
  sort:
    name: sort
    in: query
    description: Order to sort by (1 or -1).
    type: integer
  maxTimestamp:  
    name: max_timestamp
    in: query
    description: Return media before this timestamp.
    type: integer
  minTimestamp:  
    name: min_timestamp
    in: query
    description: Return media after this timestamp.
    type: integer
    
responses:
  unauthorized:
    description: Access prohibited.