swagger: '2.0'

info:
  version: "0.0.1"
  title: Thermostat Web API

# Describe your paths here
paths:
  /:
    get:
      description: Gets information on all agents
      responses:
        200:
          description: Successful response
          schema:
              type: array
              items:
                $ref: '#/definitions/agent-info'       
  /{agentId}:
    parameters:
      - $ref: '#/parameters/agentId'    
    get:
      description: Gets information for an agent
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/agent-info'     
  /{agentId}/{vmId}:
    parameters:
      - $ref: '#/parameters/agentId'
      - $ref: '#/parameters/vmId'    
    get:
      description: Gets information for a jvm monitored by an agent
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/jvm-info'

            
  /agents:
    get:
      description: Gets information for all agents
      responses:
        200:
          description: Successful response
          schema:
              type: array
              items:
                $ref: '#/definitions/agent-info'
  /agents/{agentId}:
    parameters:
      - $ref: '#/parameters/agentId'    
    get:
      description: Gets information for an agent
      responses:
        200:
          description: Successful response
          schema:
              type: array
              items:
                $ref: '#/definitions/agent-info'               
  /agents/{agentId}/vms:
    parameters:
      - $ref: '#/parameters/agentId'   
    get:
      description: Gets information for all jvms monitored by an agent
      responses:
        200:
          description: Successful response
          schema:
              type: array
              items:
                $ref: '#/definitions/jvm-info'
  /agents/{agentId}/vms/{vmId}:
    parameters:
      - $ref: '#/parameters/agentId'
      - $ref: '#/parameters/vmId'    
    get:
      description: Gets information for a jvm monitored by an agent
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/jvm-info'
            

# Collections in 2.0: revision 3c990cdff9ad

# schema-info
# agent-config

# host-info
  /agents/{agentId}/host:
    parameters:
      - $ref: '#/parameters/agentId'
    get:
      description: Gets information for the host
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/host-info'
# network-info
# backend-info

# numa-host-info
# numa-stat
# cpu-stats
  /agents/{agentId}/host/cpu:
    parameters:
      - $ref: '#/parameters/agentId'
    get:
      description: Gets cpu information for the host
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/host-cpu-info'
# memory-stats

# vm-class-stats
# vm-gc-stats
# vm-numa-stats
# vm-cpu-stats
  /agents/{agentId}/vms/{vmId}/cpu:
    parameters:
      - $ref: '#/parameters/agentId'
      - $ref: '#/parameters/vmId'
    get:
      description: Gets most recent cpu information for the jvm
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/host-cpu-info'
      parameters:
        - name: count
          in: query
          description: Count of media to return.
          type: integer
        - name: sort
          in: query
          description: Order to sort by (1 or -1).
          type: integer          
        - name: max_timestamp
          in: query
          description: Return media before this timestamp.
          type: integer
        - name: min_timestamp
          in: query
          description: Return media after this timestamp.
          type: integer
    post:
      description: Gets most recent cpu information for the jvm
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/host-cpu-info'
      parameters:
        - name: filters
          in: body
          description: Key, Comparator, Value trios to filter the data
          schema:
            $ref: '#/definitions/filters'
        - name: count
          in: query
          description: Count of media to return.
          type: integer
        - name: sort
          in: query
          description: Order to sort by (1 or -1).
          type: integer                 
    put:
      description: Adds cpu information for the jvm
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/host-cpu-info'

# vm-memory-stats
# vm-io-stats
# vm-compiler-stats
# vm-heap-info
# vm-jmx-notification
# vm-jmx-notification-stats
# vm-tlab-stats


# profile-status
# profile-info

# vm-thread-summary
# vm-thread-session
# vm-thread-state

# vm-thread-lock
# vm-deadlock-data

# vm-thread-harvesting TODO: Improve collection schema and function

# vm-info

definitions:
  filters:
    type: array
    items:
      $ref: '#/definitions/filter'
  filter:
    type: object
    properties:
      key:
        type: string
      comparator:
        type: string
      value:
        type: string
    required:
      - key
      - comparator
      - value

  agent-info:
    type: object
    
  host-info:
    type: object
  host-cpu-info:
    type: object
    
  jvm-info:
    type: object
    properties:
      _id:
        type: object
        properties:
          "$oid":
            type: string
        required:
        - "$oid"
      agentId:
        type: string
      vmId:
        type: string
      vmPid:
        type: integer
      startTimeStamp:
        type: object
        properties:
          "$numberLong":
            type: string
        required:
        - "$numberLong"
      stopTimeStamp:
        type: object
        properties:
          "$numberLong":
            type: string
        required:
        - "$numberLong"
      javaVersion:
        type: string
      javaHome:
        type: string
      mainClass:
        type: string
      javaCommandLine:
        type: string
      vmName:
        type: string
      vmArguments:
        type: string
      vmInfo:
        type: string
      vmVersion:
        type: string
      propertiesAsArray:
        type: array
        items:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
          required:
          - key
          - value
      environmentAsArray:
        type: array
        items:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
          required:
          - key
          - value
      loadedNativeLibraries:
        type: array
        items:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
          required:
          - key
          - value
      uid:
        type: object
        properties:
          "$numberLong":
            type: string
        required:
        - "$numberLong"
      username:
        type: string
    required:
      - _id
      - agentId
      - vmId
      - vmPid
      - startTimeStamp
      - stopTimeStamp
      - javaVersion
      - javaHome
      - mainClass
      - javaCommandLine
      - vmName
      - vmArguments
      - vmInfo
      - vmVersion
      - propertiesAsArray
      - environmentAsArray
      - loadedNativeLibraries
      - uid
      - username

parameters:
  agentId:
    name: agentId
    in: path
    description: The agent identification number
    type: number
    required: true
  vmId:
    name: vmId
    in: path
    description: The jvm identification number
    type: number
    required: true    