swagger: '2.0'
info:
  version: 1.0.0
  title: Thermostat Web API
  license:
    name: GPL v2 with Classpath Exception
    url: 'http://www.gnu.org/licenses'
consumes:
  - application/json
produces:
  - application/json
  - text/html; charset=utf-8
basePath: /api/1/0/0/

paths:
  '/{namespace}/systems':
    parameters:
    - $ref: '#/parameters/namespace'
    - $ref: '#/parameters/limit'
    - $ref: '#/parameters/offset'
    - $ref: '#/parameters/sort'
    get:
      description: 'Gets system information'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/system-info'
    put:
      description: 'Add or update system information'
      parameters:
        - $ref: '#/parameters/system-info'
      responses:
        '200':
          description: OK
    post:
      description: 'Query system information'
      parameters:
        - $ref: '#/parameters/query'
      responses:
        '200':
          description: OK
          schema:
            - $ref: '#/definitions/system-info'
    delete:
      description: 'Delete system information'
      responses:
        '200':
          description: OK
        
  '/{namespace}/systems/{systemId}/agents/{agentId}':
    parameters:
      - $ref: '#/parameters/namespace'
      - $ref: '#/parameters/system-id'
      - $ref: '#/parameters/agent-id'
    get:
      description: >-
        Gets information for an agent.
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/sort'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/agent-info'
        '401':
          $ref: '#/responses/unauthorized'
    put:
      description: Adds or updates information for the agent
      parameters:
        - $ref: '#/parameters/agent-info'
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/responses/unauthorized'
    delete:
      description: Deletes information for the agent
      responses:
        '200':
          $ref: '#/responses/ok'
        '401':
          $ref: '#/responses/unauthorized'

  '/{namespace}/system/{systemId}/agents/{agentId}/vms/{vmId}':
    parameters:
      - $ref: '#/parameters/namespace'
      - $ref: '#/parameters/system-id'
      - $ref: '#/parameters/agent-id'
      - $ref: '#/parameters/vm-id'
    get:
      description: Gets information for a jvm monitored by an agent
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/sort'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/vm-info'
        '401':
          $ref: '#/responses/unauthorized'

definitions:
  filters:
    type: array
    items:
      $ref: '#/definitions/filter'
  filter:
    type: object
    properties:
      key:
        type: string
      comparator:
        type: string
      value:
        type: string
    required:
      - key
      - comparator
      - value

  agent-info:
    type: object

  system-info:
    type: object
 
  vm-info:
    type: object

parameters:
  namespace:
    name: namespace
    in: path
    description: The namespace
    type: string
    required: true
    
  system-id:
    name: systemId
    in: path
    description: The system identity
    type: string
    required: true
  agent-id:
    name: agentId
    in: path
    description: The agent identity
    type: string
    required: true
  vm-id:
    name: vmId
    in: path
    description: The jvm identity
    type: string
    required: true
    
  query:
    name: query
    in: body
    description: Query for information
    required: true
    schema:
      $ref: '#/definitions/agent-info'

  agent-info:
    name: agentInfo
    in: body
    description: The agent information
    required: true
    schema:
      $ref: '#/definitions/agent-info'

  system-info:
    name: systemInfo
    in: body
    description: The system information
    required: true
    schema:
      $ref: '#/definitions/system-info'

  tags:
    name: tags
    in: query
    description: CSV of tags
    type: string
  limit:
    name: limit
    in: query
    description: Limit of items to return.
    type: integer
  offset:
    name: offset
    in: query
    description: Offset of items to return.
    type: integer    
  filters:
    name: filters
    in: body
    description: 'Key, Comparator, Value trios to filter the data'
    schema:
      $ref: '#/definitions/filters'
  sort:
    name: sort
    in: query
    description: Sort string  
    type: string

responses:
  ok:
    description: OK
  unauthorized:
    description: Access prohibited.
